version: '2'

services:
  cookus-api:
    build: .
    container_name: cookus-api
    ports:
      - "8000:80"
    networks:
      - cookus-network
      # - bridge-network
    environment:
      MYSQL_SERVER_NAME: cookus-db
    # env_file:
    #   - cookus.env
    depends_on:
      - cookus-db

  cookus-db:
    image: mysql:latest
    container_name: cookus-db
    # env_file:
    #   - cookus.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cookus
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./SQLBindedVolume:/var/lib/mysql
    networks:
      - cookus-network

  cookus-migration:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    environment:
      MYSQL_SERVER_NAME: cookus-db
    container_name: cookus-migration
    # env_file:
    #   - cookus.env
    networks:
      - cookus-network
    tty:
      true
    # command: bash -c "/root/.dotnet/tools/dotnet-ef database update"
    depends_on:
      - cookus-db

networks:
  cookus-network:
    driver: bridge
  # bridge-network:
  #   driver: bridge