version: '2'

services:
  cookus-api:
    build: .
    container_name: cookus-api
    ports:
      - "8000:80"
    networks:
      - cookus-network
    environment:
      MYSQL_SERVER_NAME: ${MYSQL_SERVER_NAME}
    env_file:
      - cookus.env
    depends_on:
      - cookus-db

  cookus-db:
    image: mysql:latest
    container_name: ${MYSQL_SERVER_NAME}
    env_file:
      - cookus.env
    volumes:
      - ./SQLBindedVolume:/var/lib/mysql
    networks:
      - cookus-network

  cookus-migration:
    build: 
      context: .
      dockerfile: Dockerfile.migration
    environment:
      MYSQL_SERVER_NAME: ${MYSQL_SERVER_NAME}
    container_name: cookus-migration
    env_file:
      - cookus.env
    networks:
      - cookus-network
    tty:
      true
    depends_on:
      - cookus-db

networks:
  cookus-network:
    driver: bridge